"""add raw_content and original_filename to resumes

Revision ID: 666afd7ba97d
Revises: 
Create Date: 2026-04-24 01:45:26.923411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '666afd7ba97d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('raw_content', sa.LargeBinary(), nullable=True))
    op.add_column('resumes', sa.Column('original_filename', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resumes', 'original_filename')
    op.drop_column('resumes', 'raw_content')
    # ### end Alembic commands ###
